# Generated by Django 4.2.5 on 2023-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='importe_total',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
