# Generated by Django 4.2.5 on 2023-10-09 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='perfil_default.png', upload_to='users/')),
                ('direccion_calle', models.CharField(blank=True, max_length=100)),
                ('direccion_otros', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion_alternativa', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-id'],
            },
        ),
    ]
